"""Built-in material scientific-model contracts and provider."""

from .builtin import (
    BUILTIN_MATERIAL_RULEBOOK_PROVIDER_ID,
    BuiltinMaterialRulebookProvider,
    context_predicate,
)
from .classification import (
    CLASSIFICATION_RULES,
    CalculationGroup,
    ClassificationMatch,
    ClassificationRule,
    classify_canonical_content,
    classify_component,
)
from .contracts import (
    MATERIAL_CONTRACT_VERSION,
    MATERIAL_SEPARATION_FATE,
    MATERIAL_STATE_TRANSITION,
    AssociationTarget,
    AssociationTargetKind,
    ComponentFate,
    ComponentSnapshot,
    MaterialDecision,
    MaterialRelation,
    MaterialModelPayload,
    OperationSnapshot,
    OutputRoleSnapshot,
    QuantitySnapshot,
    RelationshipSnapshot,
    RelationshipTransition,
    SeparationDecision,
    StateTransitionDecision,
    empty_material_mapping,
)
from .coordinator import (
    CoordinatedDecision,
    CoordinationStatus,
    MaterialEffectCoordinator,
    SepEffectCoordinator,
)
from .rulebook import (
    RelationshipTransitionMatch,
    RulebookOutcome,
    SeparationFateMatch,
    resolve_relationship_transition_rule,
    resolve_separation_fate_rule,
    output_label,
)
from .validation import (
    MaterialValidationIssue,
    MaterialValidationResult,
    proposal_type_issue,
    validate_separation_decision,
    validate_state_transition_decision,
    validate_material_result,
)

__all__ = [
    "BUILTIN_MATERIAL_RULEBOOK_PROVIDER_ID",
    "MATERIAL_CONTRACT_VERSION",
    "MATERIAL_SEPARATION_FATE",
    "MATERIAL_STATE_TRANSITION",
    "AssociationTarget",
    "AssociationTargetKind",
    "BuiltinMaterialRulebookProvider",
    "CLASSIFICATION_RULES",
    "CalculationGroup",
    "ClassificationMatch",
    "ClassificationRule",
    "ComponentFate",
    "ComponentSnapshot",
    "CoordinatedDecision",
    "CoordinationStatus",
    "MaterialDecision",
    "MaterialEffectCoordinator",
    "MaterialRelation",
    "MaterialModelPayload",
    "MaterialValidationIssue",
    "MaterialValidationResult",
    "OperationSnapshot",
    "OutputRoleSnapshot",
    "QuantitySnapshot",
    "RelationshipSnapshot",
    "RelationshipTransition",
    "RelationshipTransitionMatch",
    "RulebookOutcome",
    "SeparationFateMatch",
    "SepEffectCoordinator",
    "SeparationDecision",
    "StateTransitionDecision",
    "classify_canonical_content",
    "classify_component",
    "context_predicate",
    "empty_material_mapping",
    "output_label",
    "proposal_type_issue",
    "resolve_relationship_transition_rule",
    "resolve_separation_fate_rule",
    "validate_material_result",
    "validate_separation_decision",
    "validate_state_transition_decision",
]
